version: "3.6"
services:
  postgres:
    container_name: myblog
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "testtest"
    ports:
      - "16543:80"
    depends_on:
      - postgres
